# Products
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - nombre
        - precio
      properties:
        id:
          type: string
          description: Identificador autogenerado de cada Producto
        nombre:
          type: string
          description: Nombre o Titulo de un Producto
        precio:
          type: number
          description: Valor numerico de cada Producto
      example:
        id: 1679531656193-90794223
        nombre: leche
        precio: 200